runtime: python
env: flex
entrypoint: gunicorn -b $PORT ingest-app.py
service: default
manual_scaling:
  instances: 1

env_variables:
  CLOUD_STORAGE_BUCKET: pokoyakazan-test-01

handlers:
- url: /ingest
  script: ingest-app.app

- url: /.*
  script: ingest-app.app
